version: "3.1"
services:
  mongo:
    image: mongo
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: "${POSTGRES_DB:-postgres}"
  #     POSTGRES_USER: "${POSTGRES_USER:-user}"
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-1234}"
  #   ports:
  #     - "${POSTGRES_PORT:-5433}:5432"
